source 'https://rubygems.org'

gem 'rails', '4.1.4'

gem 'rails-api'

gem 'spring', :group => :development

gem 'mongoid'

group :development do
  # To use debugger
  gem 'debugger2'
end

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.1.2'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
gem 'unicorn'
gem 'unicorn-rails'

# Deploy with Capistrano
# gem 'capistrano', :group => :development
